services:
    victoire_core.widget_snake_content_resolver:
        class: Victoire\Widget\SnakeBundle\Resolver\WidgetSnakeContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Snake }

    victoire.widget.snake:
        class: Victoire\Widget\SnakeBundle\Entity\WidgetSnake

    victoire.widget.form.snake:
        class: Victoire\Widget\SnakeBundle\Form\WidgetSnakeType
        tags:
            - { name: form.type, alias: victoire_widget_form_snake }
