services:
    victoire.widget.snake:
        class: Victoire\Widget\SnakeBundle\Entity\WidgetSnake

    victoire.widget.form.snake:
        class: Victoire\Widget\SnakeBundle\Form\WidgetSnakeType
        tags:
            - { name: form.type, alias: victoire_widget_form_snake }
